--<ScriptOptions statementTerminator=";"/>
CREATE SCHEMA "subject";

CREATE TABLE "subject"."comment" (
		"COMMENTID" BIGINT DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		"USERID" BIGINT NOT NULL,
		"PAGEID" BIGINT NOT NULL,
		"PARENTID" BIGINT,
		"CONTENT" CLOB(2147483647),
		"CREATED" TIMESTAMP DEFAULT current_timestamp NOT NULL,
		"UPDATED" TIMESTAMP DEFAULT current_timestamp
	);

CREATE TABLE "subject"."spaceuser" (
		"SPACEUSERID" BIGINT DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		"SPACEID" BIGINT NOT NULL,
		"USERID" BIGINT NOT NULL
	);

CREATE TABLE "subject"."page" (
		"PAGEID" BIGINT DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		"USERID" BIGINT NOT NULL,
		"SPACEID" BIGINT NOT NULL,
		"PARENTID" BIGINT,
		"NAME" VARCHAR(1024) NOT NULL,
		"CONTENT" CLOB(2147483647),
		"CREATED" TIMESTAMP DEFAULT current_timestamp NOT NULL,
		"UPDATED" TIMESTAMP DEFAULT current_timestamp
	);

CREATE TABLE "subject"."attachment" (
		"ATTACHMENTID" BIGINT DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		"USERID" BIGINT NOT NULL,
		"PAGEID" BIGINT NOT NULL,
		"NAME" VARCHAR(1024) NOT NULL,
		"CONTENT" CLOB(2147483647),
		"CREATED" TIMESTAMP DEFAULT current_timestamp NOT NULL,
		"UPDATED" TIMESTAMP DEFAULT current_timestamp
	);

CREATE TABLE "subject"."user" (
		"USERID" BIGINT DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		"NAME" VARCHAR(1024) NOT NULL,
		"EMAIL" VARCHAR(1024) NOT NULL,
		"SALT" VARCHAR(1024) NOT NULL,
		"HASH" VARCHAR(1024) NOT NULL,
		"CREATED" TIMESTAMP DEFAULT current_timestamp NOT NULL,
		"UPDATED" TIMESTAMP DEFAULT current_timestamp
	);

CREATE TABLE "subject"."space" (
		"SPACEID" BIGINT DEFAULT AUTOINCREMENT: start 1 increment 1 NOT NULL GENERATED ALWAYS AS IDENTITY  (START WITH 1 ,INCREMENT BY 1),
		"NAME" VARCHAR(1024) NOT NULL,
		"CREATED" TIMESTAMP DEFAULT current_timestamp NOT NULL,
		"UPDATED" TIMESTAMP DEFAULT current_timestamp,
		"DESCRIPTION" VARCHAR(1024)
	);

CREATE INDEX "subject"."COMMENT_USER_IDX" ON "subject"."comment" ("USERID" ASC);
CREATE UNIQUE INDEX "PAGE_UNQ" ON "subject"."page" ("PAGEID" ASC);
CREATE INDEX "subject"."ATTACHMENT_USER_IDX" ON "subject"."attachment" ("USERID" ASC);
CREATE UNIQUE INDEX "subject"."SPACE_UNQ" ON "subject"."space" ("SPACEID" ASC);
CREATE INDEX "subject"."ATTACHMENT_USER_IDX" ON "subject"."attachment" ("PAGEID" ASC);
CREATE INDEX "subject"."COMMENT_PAGE_IDX" ON "subject"."comment" ("PAGEID" ASC);
CREATE UNIQUE INDEX "subject"."ATTACHMENT_UNQ" ON "subject"."attachment" ("ATTACHMENTID" ASC);
CREATE INDEX "subject"."SPACEUSER_SPACE_IDX" ON "subject"."spaceuser" ("SPACEID" ASC);
CREATE UNIQUE INDEX "subject"."COMMENT_UNQ" ON "subject"."comment" ("COMMENTID" ASC);
CREATE INDEX "subject"."PAGE_SPACE_IDX" ON "subject"."page" ("SPACEID" ASC);
CREATE INDEX "subject"."SPACEUSER_USER_IDX" ON "subject"."spaceuser" ("USERID" ASC);
CREATE UNIQUE INDEX "subject"."SPACEUSER_UNQ" ON "subject"."spaceuser" ("SPACEUSERID" ASC);
CREATE UNIQUE INDEX "subject"."USER_USER_UNQ" ON "subject"."user" ("USERID" ASC);
CREATE UNIQUE INDEX "subject"."USER_EMAIL_UNQ" ON "subject"."user" ("EMAIL" ASC);
CREATE INDEX "subject"."PAGE_USER_IDX" ON "subject"."page" ("USERID" ASC);

ALTER TABLE "subject"."page" ADD CONSTRAINT "PAGE_PK" PRIMARY KEY ("PAGEID");
ALTER TABLE "subject"."attachment" ADD CONSTRAINT "ATTACHMENT_PK" PRIMARY KEY ("ATTACHMENTID");
ALTER TABLE "subject"."user" ADD CONSTRAINT "USER_PK" PRIMARY KEY ("USERID");
ALTER TABLE "subject"."comment" ADD CONSTRAINT "COMMENT_PK" PRIMARY KEY ("COMMENTID");
ALTER TABLE "subject"."space" ADD CONSTRAINT "SPACE_PK" PRIMARY KEY ("SPACEID");
ALTER TABLE "subject"."spaceuser" ADD CONSTRAINT "SPACEUSER_PK" PRIMARY KEY ("SPACEUSERID");
ALTER TABLE "subject"."page" ADD CONSTRAINT "PAGE_SPACE_FK" FOREIGN KEY ("SPACEID") REFERENCES "subject"."space" ("SPACEID");
ALTER TABLE "subject"."comment" ADD CONSTRAINT "COMMENT_USER_FK" FOREIGN KEY ("USERID") REFERENCES "subject"."user" ("USERID");
ALTER TABLE "subject"."page" ADD CONSTRAINT "PAGE_USER_FK" FOREIGN KEY ("USERID") REFERENCES "subject"."user" ("USERID");
ALTER TABLE "subject"."comment" ADD CONSTRAINT "COMMENT_PAGE_FK" FOREIGN KEY ("PAGEID") REFERENCES "subject"."page" ("PAGEID");
ALTER TABLE "subject"."spaceuser" ADD CONSTRAINT "SPACEUSER_USER_FK" FOREIGN KEY ("USERID") REFERENCES "subject"."user" ("USERID");
ALTER TABLE "subject"."spaceuser" ADD CONSTRAINT "SPACEUSER_SPACE_FK" FOREIGN KEY ("SPACEID") REFERENCES "subject"."space" ("SPACEID");
ALTER TABLE "subject"."attachment" ADD CONSTRAINT "ATTACHMENT_PAGE_FK" FOREIGN KEY ("PAGEID") REFERENCES "subject"."page" ("PAGEID");
ALTER TABLE "subject"."attachment" ADD CONSTRAINT "ATTACHMENT_USER_FK" FOREIGN KEY ("USERID") REFERENCES "subject"."user" ("USERID");


